volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:

networks:
  havoc-network:
    driver: bridge

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: havoc-jenkins
    ports:
      - '8085:8080'
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
    networks:
      - havoc-network
  sonar:
    container_name: sonarqube
    image: sonarqube:10.3.0-community
    # Forced authentication redirect for UI is turned off for out of the box experience while trying out SonarQube
    # For real use cases delete SONAR_FORCEAUTHENTICATION variable or set SONAR_FORCEAUTHENTICATION=true
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9001:9000
      - 127.0.0.1:9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - havoc-network
#  sonarqube:
#    image: 'sonarqube:latest'
#    container_name: havoc-sonarqube
#    ports:
#      - '9000:9000'
